PBVI for more than two states
JuliaPOMDP/PointBasedValueIteration.jl pull request #5
Opened 2021-03-19 19:04 UTC by Omastto1

In this repo, the original PBVI algorithm worked only with 2 states' POMDPs and initiated its belief space uniformly at the beginning.
I made changes that fix both these problems. The changed algorithm is described [here](https://link.springer.com/content/pdf/10.1007/s10458-012-9200-2.pdf).

I am pretty sure this is far from the ideal code. However, it is a step in a good direction.

2021-03-21 00:40 UTC, zsunberg commented
Thanks! This would be great to have! It is on my list to review, but I probably won't have time to until at least next weekend. We can merge without review if someone is waiting on this, or if anyone else from juliapomdp can review, that would be helpful!

2021-03-21 11:16 UTC, dominikstrb commented
Thanks! I only had time for a first look at this PR today, but one thing we would definitely need is a test for a POMDP with more than two states. Right now, we are testing only on `TigerPOMDP` and `BabyPOMDP` which both have two states.

2021-03-23 18:04 UTC, Omastto1 commented
Hi, I made a few changes to the code, as I did not test correctly last time I pushed my changes.
As for now, the tests are failing because the MiniHallway problem is not yet pushed into the main branch on POMDPModels.
Furthermore, I want to believe that the algorithm works correctly now, but all 4 solvers that I tested with are giving me different value functions for the MH problem. 
When testing with optimal actions (instead of values) of belief, the results seem to be more or less correct but cannot be tested easily. The reason is following:
From belief vector with deterministic state say 8, action 2 results into state 5, from which actions lead to 1, 6, 8.
Action 3 results into state 7, from which actions lead to 1, 8, 6. 
Which (in my opinion) is both the same result. However, one solver takes into account ordered actions, where the other does not.

The solver is still far from being ready, and I am unsure when I will finish it, but it is another step ahead.

2021-03-23 18:09 UTC, Omastto1 commented
At this moment, the solver also contains two functions that should be doing the same as `BeliefUpdaters.update(::DiscreteUpdater, DiscreteBelief,...)` but I had problems with the error it produces when the sum of the new belief is zero. I was able to wrap the call into a try-catch block once, but then it did not work the second time. I will probably return to this later on.

2021-03-28 01:15 UTC, zsunberg commented
@Omastto1 thanks again for your work on this!

> The solver is still far from being ready, and I am unsure when I will finish it, but it is another step ahead.

Since you say that it is not ready yet, I'll hold off on doing a detailed review. Let me know if you want me to look at specific parts.

> As for now, the tests are failing because the MiniHallway problem is not yet pushed into the main branch on POMDPModels.

You could use the `@test_broken` macro for now so that the other tests can still pass

> When testing with optimal actions (instead of values) of belief, the results seem to be more or less correct but cannot be tested easily. The reason is following:
> From belief vector with deterministic state say 8, action 2 results into state 5, from which actions lead to 1, 6, 8.
> Action 3 results into state 7, from which actions lead to 1, 8, 6.
> Which (in my opinion) is both the same result. However, one solver takes into account ordered actions, where the other does not.

Yes, indeed, it seems like those two actions have the same consequences. That is why it is important to compare value functions and not actions as discussed in JuliaPOMDP/POMDPs.jl#339.

2021-03-28 18:55 UTC, Omastto1 commented
Even if I would love to say the solver works correctly now, the output of this version's value function is approx. 3.4 times greater than the opposite of the SARSOP solver, which could suggest that it is OK, but looking at it critically can also mean the opposite.

If I somehow solve this and have some time left, I would like to optimize it using profiling.

2021-04-04 00:25 UTC, zsunberg commented
Ok, now that the MiniHallway has been registered, I have restarted the build.

2021-04-04 00:35 UTC, zsunberg requested changes
I added some more comments that should be fixed before this is merged.

Also, the tests that test whether the value function matches with SARSOP do need to pass before we can merge this.

2021-04-04 00:35 UTC, zsunberg commented on src/pbvi.jl
> +            end
Try-catch without any indication if something goes wrong is not very good coding practice :) You WANT your code to tell you if there is an assumption that is wrong. You should at least output a warning if something goes wrong, and you need to understand why it is going wrong.

2021-04-04 00:35 UTC, zsunberg commented on src/pbvi.jl
> +    B_new = deepcopy(B)
`deepcopy` is sometimes unnecessarily slow because it has to create a dictionary - could we use `copy` here?

2021-04-04 00:35 UTC, zsunberg commented on src/pbvi.jl
> +            # This should work but does not, update throws error every time
What do these comments mean? Can we delete them?

2021-04-04 17:48 UTC, Omastto1 commented on src/pbvi.jl
> +            end
The `update` method throws an error in cases, where the sum of the belief vector is 0. This happened quite often as the `obs_weight` returns zero probability for some combinations of action and observation. Thus I could not run the solver properly.

In the newer version, I am using the belief update from `https://www.st.ewi.tudelft.nl/mtjspaan/pub/Walraven19jair.pdf` which uses `P(o|b, a)` as normalizing constant, and as such, I can tell whether the zero-sum issue pops up. In such cases, the `P(o|b, a)` is zero and I don't have to call belief update.

I expect this to somehow wrap into a new function. 

```
trans_probs = sum([pdf(transition(pomdp, s, a), sp) * b[stateindex(pomdp, s)] for s in states(pomdp), sp in ordered_states(pomdp)], dims=1)
for o in observations(pomdp)
    obs_probs = pdf.(map(sp -> observation(pomdp, a, sp), ordered_states(pomdp)), o)
    pr_o_given_b_a = sum(obs_probs .* trans_probs')
    if pr_o_given_b_a > 0.
        b′ = [obs_probs[stateindex(pomdp, sp)] / pr_o_given_b_a * trans_probs[stateindex(pomdp, sp)] for sp in ordered_states(pomdp)]
        if !in(b′, Bs)
            push!(succs, b′)
        end
    end
end
```

2021-04-04 17:48 UTC, Omastto1 commented on src/pbvi.jl
> +            # This should work but does not, update throws error every time
Definitely can.

2021-04-05 14:59 UTC, Omastto1 commented on src/pbvi.jl
> +    B_new = deepcopy(B)
fixed

2021-04-05 15:11 UTC, Omastto1 commented
After hours of debugging, I changed the reference solver from `SARSOP.jl` to `POMDPSolve.jl`.
The result is that all tests are passing.
(`SARSOP.jl` probably did not output optimal results?)

2021-04-07 16:28 UTC, zsunberg commented
Hmm... this is very interesting. It is surprising that they don't agree. We have maintained SARSOP a lot more. One way to see which solver is right is to run simulations to see if the average value matches up with the alpha vectors.

2021-04-07 16:49 UTC, Omastto1 commented
I have still not fully understood how I should check the correctness of results discussed in https://github.com/JuliaPOMDP/POMDPs.jl/discussions/339. The result of that discussion is to check with the value function. 

My simulations showed that the discounted reward was the same for all runs of my PBVI policy simulation and distributed between different values for the MCTS policy simulation.
How would you run the simulations?
Do you suggest simulating PBVI vs. POMDPSolve( or SARSOP) policies against each other?

2021-04-08 14:51 UTC, zsunberg commented
> How would you run the simulations?
> Do you suggest simulating PBVI vs. POMDPSolve( or SARSOP) policies against each other?

Yes, that is what I am suggesting. I'll try it out myself this weekend and send you the code if I have time.

2021-04-11 00:08 UTC, zsunberg commented
Here is the issue:
```julia
using POMDPs
using POMDPSolve: POMDPSolveSolver
using SARSOP: SARSOPSolver
using POMDPSimulators: RolloutSimulator
using POMDPModels: MiniHallway
using POMDPModelTools: Deterministic

m = MiniHallway()

p = solve(POMDPSolveSolver(), m)

s = first(states(m))
@show value(p, Deterministic(s))
@show mean([simulate(RolloutSimulator(), m, p, updater(p), Deterministic(s)) for i in 1:10_000])
# outputs 2.63 and 0.735

sarsop_p = solve(SARSOPSolver(), m)
@show value(sarsop_p, Deterministic(s))
@show mean([simulate(RolloutSimulator(), m, sarsop_p, updater(sarsop_p), Deterministic(s)) for i in 1:10_000])
# outputs 0.735 and 0.735
```

The alpha vectors from POMDPSolve do not match with the monte carlo simulations because it currently doesn't handle terminal states correctly.

I suspect that PBVI also does not. I couldn't find any calls to `isterminal` in this code.

2021-04-11 00:23 UTC, zsunberg commented
Please include a test like this: https://github.com/JuliaPOMDP/POMDPSolve.jl/blob/3da8474dedcbc726d7954b6697858198d443fa7b/test/runtests.jl#L70-L80

2021-04-11 18:23 UTC, Omastto1 commented
Not taking into account the terminal states was definitely an issue from my side. Not being included in the paper does not mean I can leave it out, a new lesson for the next time.

New test sets are evaluated correctly in 37 out of 39 tests. The remaining test cases belong to state 5 and its value and action not being same for sarsop and pbvi, which I described earlier.
In PBVI,  the resulting action is 2, which goes to state 6, from which the best action is 1, leading to 10, then action 2 to state 11 (terminal).
On the other hand, the SARSOP solve suggest action 1, which leads state 1, from which the best action is 2, leading to state 2, then action 2 again to state 3, from 3 with action 1 to state 7, from which the best action is 3 to state 10, then action 2 to state 11 (terminal).

Resulting in 3 actions to goal in PBVI and SARSOP with 6 actions.

I believe the PBVI has better result and SARSOP is approximating?

So I flagged these tests as broken.

I will make some optimizations to the code, but this time I believe it is almost good to go.

2021-04-13 04:08 UTC, zsunberg commented
Awesome! Nice work! I will see if I can think of anything that might be causing these tests to be broken.

2021-04-13 07:58 UTC, Omastto1 commented
> Awesome! Nice work! I will see if I can think of anything that might be causing these tests to be broken.

Actually, looking at the tests, the `SARSOP` solver seems to end up with 9 beliefs and 10 alpha vectors:
```
-------------------------------------------------------------------------------
 Time   |#Trial |#Backup |LBound    |UBound    |Precision  |#Alphas |#Beliefs
-------------------------------------------------------------------------------
 0.053   8       25             0.759052   0.759052   0               10            9
-------------------------------------------------------------------------------
```
I'm not familiar with the algorithm, but it seems like the algorithm was so precise that it stopped before even discovering the belief vector, which now fails the tests?

2021-04-13 18:32 UTC, zsunberg commented
Ah - good thinking! SARSOP only explores the subset of the belief space that is reachable under an optimal policy, so if certain beliefs are not in that subset, it may not have good Alpha Vectors for it.

I think it is safe to leave those tests out with a comment that briefly explains that these beliefs are not reachable under optimal policies.

2021-04-21 22:17 UTC, Omastto1 commented
The solver is ready to be pulled on my side.

2021-04-22 05:19 UTC, zsunberg reviewed
I did a quick look and had one comment. It looked good to me, but do you have any specific parts that you think could use a closer look, @Omastto1 ? @dominikstrb do you have any comments.

I think if it outputs the same results as SARSOP, which it looks like it does now, it is probably correct.

2021-04-22 05:19 UTC, zsunberg commented on test/runtests.jl
> +                    @test_broken isapprox(value(policy, Deterministic(s)), value(sarsop_policy, Deterministic(s)), rtol=0.1)
I don't think you should keep the test_broken here. Just skip it and leave a comment since we know why it does not match.

2021-04-27 13:52 UTC, dominikstrb commented
The code is readable and the tests are passing, looks good to me! Although I have not checked all the details of the implementation, I think this is good to merge. The code coverage warnings could be fixed by adding tests for

- a POMDP with SparseCat initial distribution (src/pbvi.jl#L40)
- a FixedHorizonPOMDP (src/pbvi.jl#L42-L43)

2021-04-28 12:51 UTC, Omastto1 commented
I believe it is ok to be merged.

2021-04-29 06:39 UTC, merged

2021-04-29 14:59 UTC, zsunberg commented
Awesome! Nice work!